site_name: FAIRSCAPE
site_description: An Evolving AI-readiness Framework for Biomedical Research
site_url: https://fairscape.github.io/

# Repository
repo_name: fairscape/fairscape.github.io
repo_url: https://github.com/fairscape/fairscape.github.io

# Copyright
copyright: Copyright &copy; 2024 University of Virginia

# Page tree
nav:
  - Home: index.md
  - Components:
      - Server: components/server.md
      - CLI: components/CLI.md
      - GUI: components/GUI.md
      - Web Server: components/webserver.md

theme:
  name: material
  language: en
  features:
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.footer
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang: en

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fairscape
