# Project Information
site_name: FAIRSCAPE
site_description: A Framework for FAIR and Reproducible Biomedical Analytics
site_url: https://fairscape.github.io/

copyright: Copyright &copy; 2024 THE RECTOR AND VISITORS OF THE UNIVERSITY OF VIRGINIA

# Theme Configuration
theme:
  name: readthedocs
  navigation_depth: 4

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Navigation Structure
nav:
  - Home: index.md
  - Packages:
      - MDS Server: components/server.md
      - CLI: components/CLI.md
      - GUI: components/GUI.md
      - Front-End Web Server: components/webserver.md

plugins:
  - search
